name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: plantuml  preview
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: preview
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # this job will do parallel wiht generate_plantuml
  do_some_actions_test:
    runs-on: ubuntu-latest
    name: just_test_in_parallel
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: retrieve secret 
      env:
        just_test: ${{ secrets.JUST_TEST }}
      run: ./.github/scripts/print_secret.sh $just_test
  # this job will do after generate_plantuml
  do_some_other_actions_test:
    needs: generate_plantuml
    runs-on: ubuntu-latest
    name: just_test_in_sequence
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run build script
      run: ./.github/scripts/build.sh
      shell: bash
    - name: dome some calculate
      run: | 
        expr 1 + 1 > output.log
      shell: bash
    - name: save output file
      uses: actions/upload-artifact@v2
      with:
        name: output-log-file
        path: output.log